chunk upload monitor
threeaccents/oriio pull request #1
Opened 2022-03-01 03:33 UTC by vdamrongsri

2022-03-01 12:15 UTC, threeaccents requested changes
Overall looking much better a few cleanups needed though. Also need to update the the `updated_at` on every chunk append.

2022-03-01 12:15 UTC, threeaccents commented on apps/mahi/lib/mahi/uploads/chunk_upload_montior.ex
> +    Enum.each(uploads, &maybe_terminate_upload_process/1)
This is much much better than before. If you rly wanna get elixiry I would use a for comprehension. You can filter and loop at the same time and make it clearer to the reader right away instead of jumping through functions.

```elixir
for upload <- uploads, is_upload_stale?(upload) do
    Process.exit(pid, :normal)
end

# or single line

for upload <- uploads, is_upload_stale?(upload), do:  Process.exit(pid, :normal)
```

2022-03-01 12:15 UTC, threeaccents commented on apps/mahi/lib/mahi/uploads/chunk_upload_worker.ex
> +          updated_at: Date.t()
`DateTime.t()`

2022-03-01 12:15 UTC, threeaccents commented on mix.exs
> +      {:hackney, "~> 1.0"},
why was this dependency added?

2022-03-01 12:15 UTC, threeaccents commented on apps/mahi/lib/mahi/documents.ex
> +      |> Map.put(:updated_at, DateTime.utc_now())
I would move this to the worker instead of here in the context.

2022-03-01 13:37 UTC, vdamrongsri commented on mix.exs
> +      {:hackney, "~> 1.0"},
@threeaccents for some reason it wouldn't let me compile the app without adding it...

2022-03-01 13:39 UTC, threeaccents commented on mix.exs
> +      {:hackney, "~> 1.0"},
@vdamrongsri that doesn't make much sense. Remove it and see if it works.

2022-03-01 13:41 UTC, vdamrongsri commented on apps/mahi/lib/mahi/uploads/chunk_upload_montior.ex
> +    Enum.each(uploads, &maybe_terminate_upload_process/1)
@threeaccents very cool

2022-03-01 13:54 UTC, threeaccents commented on apps/mahi/lib/mahi/uploads/chunk_upload_montior.ex
> +    for {_, pid, _} = upload <- uploads, is_upload_stale?(upload), do:  Process.exit(pid, :normal)
I didn't realize it returned a tuple. You can clean this up by doing.

```elixir
for {_, pid, state} <- uploads, is_upload_stale?(state), do: Process.exit(pid, :normal)

...

 defp is_upload_stale?(%{update_at: updated_at}) do
    valid_time = DateTime.utc_now() |> DateTime.add(-@valid_hours * 60 * 60, :second)
    DateTime.diff(valid_time, updated_at) < 0
  end
```

2022-03-01 14:27 UTC, vdamrongsri commented on mix.exs
> +      {:hackney, "~> 1.0"},
@threeaccents weird works fine, Idk how that got in there lol

2022-03-01 14:27 UTC, vdamrongsri commented on mix.exs
> +      {:hackney, "~> 1.0"},
@threeaccents removed!

2022-03-01 14:56 UTC, threeaccents commented on apps/mahi/lib/mahi/uploads/chunk_upload_worker.ex
> +          updated_at: DateTime.t()
this isn't included in the `new_chunk_upload`

2022-03-02 18:55 UTC, threeaccents commented on apps/mahi/lib/mahi/uploads/chunk_upload_worker.ex
> +  def updated_at(server) do
The APIs always go above the handle calls. You'll see the other client calls are grouped together towards the top of the file.

2022-03-02 19:20 UTC, merged