use distributed monitor for chunk upload
threeaccents/oriio pull request #4
Opened 2022-03-06 20:17 UTC by vdamrongsri

2022-03-10 19:09 UTC, threeaccents requested changes

2022-03-10 19:09 UTC, threeaccents commented on apps/oriio/lib/oriio/application.ex
> +        restart: :transient,
Not sure if we want the restart to be transient in for the monitor.

2022-03-10 19:09 UTC, threeaccents commented on apps/oriio/lib/oriio/uploads/chunk_upload_monitor/monitor.ex
> +    case GenServer.start_link(__MODULE__, [], name: via_tuple(ChunkUploadMonitor)) do
`__MODULE__` instaed of `ChunkUploadMonitor`

2022-03-10 19:09 UTC, threeaccents commented on apps/oriio/lib/oriio/uploads/chunk_upload_monitor/monitor.ex
> +  def whereis(name \\ ChunkUploadMonitor) do
Is this function used anywhere?

2022-03-10 19:13 UTC, threeaccents commented on apps/oriio/lib/oriio/uploads/chunk_upload_monitor/monitor.ex
> +    case GenServer.start_link(__MODULE__, [], name: via_tuple(ChunkUploadMonitor)) do
Since you don't alias the current module the atom that is passed into the name is `ChunkUploadMonitor` in the supervisor you do alias the monitor so the atom passed into it is `Oriio.Uploads.ChunkUploadMonitor`.

But anyways you should never reference the current module on its own and always use __MODULE__

2022-03-10 19:20 UTC, vdamrongsri commented on apps/oriio/lib/oriio/uploads/chunk_upload_monitor/monitor.ex
> +    case GenServer.start_link(__MODULE__, [], name: via_tuple(ChunkUploadMonitor)) do
@threeaccents ahhh true

2022-03-10 19:20 UTC, vdamrongsri commented on apps/oriio/lib/oriio/uploads/chunk_upload_monitor/monitor.ex
> +  def whereis(name \\ ChunkUploadMonitor) do
@threeaccents no I was just using this for testing

2022-03-10 19:35 UTC, threeaccents commented on apps/oriio/lib/oriio/application.ex
> +        id: Oriio.ClusterConnector,
Maybe name this something like `:upload_monitor_cluster_connector` or `:upload_monitor_cluster_observer`

2022-03-10 19:36 UTC, threeaccents commented on apps/oriio/lib/oriio/application.ex
> +        id: Oriio.ClusterConnector,
I would stick to a regular atom in this case. I don't like to create anonymous Module style atoms for modules that don't exist.

2022-03-10 19:36 UTC, vdamrongsri commented on apps/oriio/lib/oriio/application.ex
> +        id: Oriio.ClusterConnector,
@threeaccents agreed

2022-03-10 20:20 UTC, threeaccents commented on apps/oriio/lib/oriio/uploads/upload_monitor/monitor.ex
>    @spec start_link(any) :: :ignore | {:error, any} | {:ok, pid}
```suggestion
  @spec start_link(term()) :: :ignore | {:ok, pid()}
```

2022-03-10 20:22 UTC, threeaccents commented on apps/oriio/lib/oriio/uploads/upload_monitor/monitor.ex
>    @spec start_link(any) :: :ignore | {:error, any} | {:ok, pid}
Can't return {:error, _} so removed the return option. Surprised dialzyer didn't complain about this. And also always use parenthesis in the type. Lastly use term() instead of any()

2022-03-11 00:42 UTC, threeaccents approved these changes

2022-03-11 00:42 UTC, threeaccents commented on apps/oriio/lib/oriio/uploads/upload_monitor/monitor.ex
> +    case GenServer.start_link(__MODULE__, [], name: via_tuple(__MODULE__)) do
I wonder if this check is needed. I feel like this would never happen and maybe it should actually error if it does. Idk something to think about.

2022-03-11 02:01 UTC, merged